language: go
go:
  - "1.11"

install:
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck

env:
  - GO111MODULE=on

script:
  - go test ./...
  - go vet ./...
  # vendoring required until following tools are module aware
  - go mod vendor
  - errcheck ./...
  - golint ./...
